export default constants = {
    "SET_SEARCH_VALUE": "SET_SEARCH_VALUE",
    "SET_NUMBER": "SET_NUMBER",
    "ADD_TO_ARRAY": "ADD_TO_ARRAY",
    "ADD_NUMBER": "ADD_NUMBER",
    "CLEAR_ARRAY": "CLEAR_ARRAY",
    "SET_LOGIN_RESPONSE":"SET_LOGIN_RESPONSE"
}